config/routes.rb
Crowdfunder::Application.routes.draw do

  resources :projects do
    resources :pledges, only: [:new, :create]
  end

  resources :users, :except => [:index, :destroy]
  resource :session, :only => [:new, :create, :destroy]

  namespace :my do 
    resources :projects do # => My::ProjectsController
      resources :images, only: [:index, :create]
    end
  end
  
  root :to =>"welcome#index"
  

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

  attr_accessible :amount
  				# Note: :project_id and :user_id should not be modifiable through mass assignment

  belongs_to :user
  belongs_to :project

  # after_create :send_new_pledge_email
 
  validates :user, 		:presence => true
  validates :project, 	:presence => true

  validates :amount,  :numericality => {:only_integer => true, :greater_than => 0}, :presence => true

  # def send_new_pledge_email
  #   UserMailer.new_pledge(self).deliver
  # end
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  attr_accessible :description, :goal, :teaser, :title

  belongs_to :user
  has_many :pledges
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body


  has_many :projects
  has_many :pledges

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true, :on => :create
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def not_authenticated
  	redirect_to new_session_path, :alert => "Please login to make a pledge."
  end
end

app/controllers/my/projects_controller.rb
class My::ProjectsController < ApplicationController
  def index
  	@projects = current_user.projects 
  end

  def new
  end

  def edit
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

before_filter :require_login
before_filter :require_project

	def new
		@pledge = @project.pledges.build
	end

	def create
		@pledge = @project.pledges.build params[:pledge]
		@pledge.user = current_user

		if @pledge.save
			UserMailer.new_pledge(@pledge).deliver
			redirect_to @project, notice: "Thank-you for pledging."
		else
			render :new
		end
	end

	protected

	def require_project
		@project = Project.find params[:project_id]
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
  	@projects = Project.all
  end

  def show
  	@project = Project.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # Login page
  def new
    
  end

  # Login submit action
  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to :root, :notice => "Welcome back"
    else
      flash.now[:alert] = "Invalid credentials. Try again?"
      render :new
    end
  end

  # Logout submit
  def destroy
    logout
    redirect_to :root, notice: "Bye... Hope to see you later!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      auto_login(@user) # Log them in right away. No account verification required
      redirect_to root_path, :notice => "Account created."
    else
      render :new
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my/projects_helper.rb
module My::ProjectsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
	end

	

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">CrowdFunder</a>
    <ul class="nav">
      <li class="<%= 'active' if params[:controller] == 'welcome'%>"><a href="/">Home</a></li>
      <li class="<%= 'active' if params[:controller] == 'projects' %>">
        <%= link_to "Projects", projects_url %>
      </li>
       <% if logged_in? %>
         <li class="<%= 'active' if params[:controller] == 'my/projects'%>">
          <%= link_to "My Projects", my_projects_url %>
        </li>
      <% end %>
    </ul>

      <div class="pull-right">
        <% if logged_in? %>
          <%= link_to 'Logout', :session, :method => :delete, class: 'btn' %>
        <% else %>
          <%= link_to 'Sign Up', [:new, :user], class: 'btn btn-primary' %>
          <%= link_to 'Sign In', [:new, :session], class: 'btn btn-success' %>
        <% end %>
      </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "/layouts/nav" %>

       <% if flash[:alert] %>
        <div class="alert alert-error">
          <%= flash[:alert] %>
        </div>
      <% end %>


      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>


    <%= yield %>
  </div>
</body>
</html>

app/views/my/projects/index.html.erb
<h1>My Projects</h1>
<p>Manage all of your projects here.</p>

<ul>
	<% @projects.each do |project| %>
		<li><%= project.title %></li>
		<% end %>

</ul>

app/views/pledges/new.html.erb
<h1>Pledge For <%= @project.title %></h1>

<%= form_for [@project, @pledge] do |f| %>
 
	<%=render 'shared/form_errors', :f => f %>

	<%= f.label :amount %>
	<%= f.text_field :amount %>

	<div class="form-actions">
		<%= f.submit 'Pledge Now', :class => 'btn' %>
	</div>

	<% end %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<ul>
	<% @projects.each do |project| %>
	  <li>
	    <%= link_to project.title, project %>
	    <br>
	    <%= project.teaser %>
	  </li>
	<% end %>
</ul>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p>
	A project by <%= @project.user.first_name %> <%= @project.user.last_name %>
</p>

<hr/>

<%= link_to 'Back This Project', [:new, @project, :pledge], class: 'btn btn-success btn-large' %>
							<!-- new_project_pledge_path(@project) -->



<!-- On the project page I see a form with a text field for the amount and a button called ‘Pledge Now’
I am logged in
If I am not logged in, clicking on ‘Pledge Now’ takes me to the login page
The amount is an integer (no decimals)
The currency is CAD -->

app/views/shared/_form_errors.html.erb
<% unless f.object.errors.empty? %>
	<div class="alert alert-error">
		<strong>Try again after fixing the following things:</strong><br/>
		<ul>
			<% f.object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up for an Account</h1>
<p>Fill in your information below</p>

<hr/>


<%= form_for @user do |f| %>

  <div class="span6">


    <%=render 'shared/form_errors', :f => f %>

    <%= f.text_field :first_name, placeholder: "First Name", class: "input-block-level" %>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "input-block-level" %>

    <%= f.email_field :email, placeholder: "E-mail Address", class: "input-block-level" %>
    <%= f.password_field :password, placeholder: "Password", class: "input-block-level" %>
    
    <div class="form-actions">
      <%= f.submit 'Create Account', class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/welcome/index.html.erb
"hello"